spring:
  application:
    name: weather
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
server:
  port: 8094
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.weather.model

weather:
  api:
    url: "https://apihub.kma.go.kr/api/typ02/openApi/VilageFcstInfoService_2.0/getVilageFcst"
    key: "qFa9zsi_T0CWvc7Ivz9ANQ"